apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-stuff
  labels:
    app: private-stuff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-stuff
  template:
    metadata:
      labels:
        app: private-stuff
    spec:
      containers:
      - name: nginx
        image: my_bucket_name/private-image:latest
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: local-registry
      # This is assuming you created a secret called local-registry